

export default {content: [
  './index.html',
  './src/**/*.{js,ts,jsx,tsx}'
],
  theme: {
    extend: {
      colors: {
        'color-black': 'var(--color-black)',
        'color-white': 'var(--color-white)',
        'color-grey-900': 'var(--color-grey-900)',
        'color-grey-800': 'var(--color-grey-800)',
        'color-grey-500': 'var(--color-grey-500)',
        'color-grey-300': 'var(--color-grey-300)',
        'color-grey-200': 'var(--color-grey-200)',
        'color-grey-100': 'var(--color-grey-100)',
        'color-blue-50': 'var(--color-blue-50)',
        'color-blue-100': 'var(--color-blue-100)',
        'color-blue-200': 'var(--color-blue-200)',
        'color-blue-300': 'var(--color-blue-300)',
        'color-blue-400': 'var(--color-blue-400)',
        'color-blue-500': 'var(--color-blue-500)',
        'color-blue-600': 'var(--color-blue-600)',
        'color-blue-700': 'var(--color-blue-700)',
        'color-blue-800': 'var(--color-blue-800)',
        'color-blue-900': 'var(--color-blue-900)',
        'color-blue-950': 'var(--color-blue-950)',
        'color-red-500': 'var(--color-red-500)',
        'color-beast-accent-gold': 'var(--color-beast-accent-gold)',
        'color-beast-accent-blue': 'var(--color-beast-accent-blue)',
        'color-beast-accent-blue-dark': 'var(--color-beast-accent-blue-dark)',
        'color-black-alpha-05': 'var(--color-black-alpha-05)',
        'color-black-alpha-10': 'var(--color-black-alpha-10)',
        'color-black-alpha-25': 'var(--color-black-alpha-25)',
        'color-black-alpha-50': 'var(--color-black-alpha-50)',
        'color-black-alpha-75': 'var(--color-black-alpha-75)',
        'color-bg-body': 'var(--color-bg-body)',
        'color-bg-surface': 'var(--color-bg-surface)',
        'color-bg-inverse': 'var(--color-bg-inverse)',
        'color-bg-accent': 'var(--color-bg-accent)',
        'color-text-primary': 'var(--color-text-primary)',
        'color-text-secondary': 'var(--color-text-secondary)',
        'color-text-tertiary': 'var(--color-text-tertiary)',
        'color-text-inverse': 'var(--color-text-inverse)',
        'color-text-accent': 'var(--color-text-accent)',
        'color-text-link': 'var(--color-text-link)',
        'color-border-subtle': 'var(--color-border-subtle)',
        'color-border-default': 'var(--color-border-default)',
        'color-border-strong': 'var(--color-border-strong)',
        'color-border-inverse': 'var(--color-border-inverse)',
        'color-border-focus': 'var(--color-border-focus)',
        'color-state-error': 'var(--color-state-error)',
        'color-state-disabled': 'var(--color-state-disabled)',
        'color-overlay-light': 'var(--color-overlay-light)',
        'color-overlay-dark': 'var(--color-overlay-dark)',
        'color-icon-primary': 'var(--color-icon-primary)',
        'color-icon-secondary': 'var(--color-icon-secondary)',
        'color-icon-inverse': 'var(--color-icon-inverse)',
        'color-icon-accent': 'var(--color-icon-accent)',
        'color-icon-disabled': 'var(--color-icon-disabled)',
        'color-button-primary-bg-default': 'var(--color-button-primary-bg-default)',
        'color-button-primary-bg-hover': 'var(--color-button-primary-bg-hover)',
        'color-button-primary-text': 'var(--color-button-primary-text)',
        'color-button-primary-text-hover': 'var(--color-button-primary-text-hover)',
        'color-button-primary-border': 'var(--color-button-primary-border)',
        'color-button-secondary-bg-default': 'var(--color-button-secondary-bg-default)',
        'color-button-secondary-bg-hover': 'var(--color-button-secondary-bg-hover)',
        'color-button-bg-disabled': 'var(--color-button-bg-disabled)',
        'color-button-border-disabled': 'var(--color-button-border-disabled)',
        'color-button-text-disabled': 'var(--color-button-text-disabled)',
        'color-ink': 'var(--color-ink)',
        'color-surface': 'var(--color-surface)',
        'color-muted': 'var(--color-muted)',
        'color-border': 'var(--color-border)',
        'color-disabled-bg': 'var(--color-disabled-bg)',
        'color-disabled-text': 'var(--color-disabled-text)',
        'color-error': 'var(--color-error)',
        'color-accent': 'var(--color-accent)',
        'color-pill-light': 'var(--color-pill-light)',
        'color-pill-mid': 'var(--color-pill-mid)',
        ink: 'var(--color-ink)',
        surface: 'var(--color-surface)',
        muted: 'var(--color-muted)',
        'ds-border': 'var(--color-border)',
        'disabled-bg': 'var(--color-disabled-bg)',
        'disabled-text': 'var(--color-disabled-text)',
        error: 'var(--color-error)',
        accent: 'var(--color-accent)',
        'pill-light': 'var(--color-pill-light)',
        'pill-mid': 'var(--color-pill-mid)',
        black: 'var(--color-black)',
        white: 'var(--color-white)',
        grey: {
          '100': 'var(--color-grey-100)',
          '200': 'var(--color-grey-200)',
          '300': 'var(--color-grey-300)',
          '500': 'var(--color-grey-500)',
          '800': 'var(--color-grey-800)',
          '900': 'var(--color-grey-900)'
        },
        blue: {
          '50': 'var(--color-blue-50)',
          '100': 'var(--color-blue-100)',
          '200': 'var(--color-blue-200)',
          '300': 'var(--color-blue-300)',
          '400': 'var(--color-blue-400)',
          '500': 'var(--color-blue-500)',
          '600': 'var(--color-blue-600)',
          '700': 'var(--color-blue-700)',
          '800': 'var(--color-blue-800)',
          '900': 'var(--color-blue-900)',
          '950': 'var(--color-blue-950)'
        },
        red: {
          '500': 'var(--color-red-500)'
        },
        gold: 'var(--color-beast-accent-gold)',
        'beast-blue': 'var(--color-beast-accent-blue)',
        'beast-blue-dark': 'var(--color-beast-accent-blue-dark)',
        'bg-body': 'var(--color-bg-body)',
        'bg-surface': 'var(--color-bg-surface)',
        'bg-inverse': 'var(--color-bg-inverse)',
        'bg-accent': 'var(--color-bg-accent)',
        'fg-primary': 'var(--color-text-primary)',
        'fg-secondary': 'var(--color-text-secondary)',
        'fg-tertiary': 'var(--color-text-tertiary)',
        'fg-inverse': 'var(--color-text-inverse)',
        'fg-accent': 'var(--color-text-accent)',
        'fg-link': 'var(--color-text-link)',
        'bd-subtle': 'var(--color-border-subtle)',
        'bd-default': 'var(--color-border-default)',
        'bd-strong': 'var(--color-border-strong)',
        'bd-inverse': 'var(--color-border-inverse)',
        'bd-focus': 'var(--color-border-focus)',
        'state-error': 'var(--color-state-error)',
        'state-disabled': 'var(--color-state-disabled)',
        'overlay-light': 'var(--color-overlay-light)',
        'overlay-dark': 'var(--color-overlay-dark)',
        'icon-primary': 'var(--color-icon-primary)',
        'icon-secondary': 'var(--color-icon-secondary)',
        'icon-inverse': 'var(--color-icon-inverse)',
        'icon-accent': 'var(--color-icon-accent)',
        'icon-disabled': 'var(--color-icon-disabled)',
        'btn-primary-bg': 'var(--color-button-primary-bg-default)',
        'btn-primary-bg-hover': 'var(--color-button-primary-bg-hover)',
        'btn-primary-text': 'var(--color-button-primary-text)',
        'btn-primary-text-hover': 'var(--color-button-primary-text-hover)',
        'btn-primary-border': 'var(--color-button-primary-border)',
        'btn-secondary-bg': 'var(--color-button-secondary-bg-default)',
        'btn-secondary-bg-hover': 'var(--color-button-secondary-bg-hover)',
        'btn-disabled-bg': 'var(--color-button-bg-disabled)',
        'btn-disabled-border': 'var(--color-button-border-disabled)',
        'btn-disabled-text': 'var(--color-button-text-disabled)'
      },
      spacing: {
        '0': 'var(--spacing-0)',
        '1': 'var(--spacing-4)',
        '2': 'var(--spacing-8)',
        '3': 'var(--spacing-12)',
        '4': 'var(--spacing-16)',
        '5': 'var(--spacing-20)',
        '6': 'var(--spacing-24)',
        '8': 'var(--spacing-32)',
        '10': 'var(--spacing-40)',
        '12': 'var(--spacing-48)',
        '16': 'var(--spacing-64)',
        '20': 'var(--spacing-80)',
        '24': 'var(--spacing-96)',
        '32': 'var(--spacing-128)'
      },
      borderRadius: {
        none: 'var(--radius-none)',
        sm: 'var(--radius-small)',
        DEFAULT: 'var(--radius-small)',
        md: 'var(--radius-medium)',
        lg: 'var(--radius-medium)',
        xl: 'var(--radius-large)',
        full: 'var(--radius-pill)'
      },
      borderWidth: {
        '1': 'var(--stroke-thin)',
        '2': 'var(--stroke-default)',
        DEFAULT: 'var(--stroke-thin)'
      },
      fontSize: {
        '13': ['var(--size-13)', { lineHeight: '1.4' }],
        '15': ['var(--size-15)', { lineHeight: '1.5' }],
        '28': ['var(--size-28)', { lineHeight: '1.2' }],
        '32': ['var(--size-32)', { lineHeight: '1.2' }],
        '34': ['var(--size-34)', { lineHeight: '1.1' }],
        '40': ['var(--size-40)', { lineHeight: '1.1' }],
        xs: ['var(--size-12)', { lineHeight: '1.4' }],
        sm: ['var(--size-14)', { lineHeight: '1.5' }],
        base: ['var(--size-16)', { lineHeight: '1.5' }],
        lg: ['var(--size-18)', { lineHeight: '1.5' }],
        xl: ['var(--size-20)', { lineHeight: '1.4' }],
        '2xl': ['var(--size-24)', { lineHeight: '1.3' }],
        '3xl': ['var(--size-30)', { lineHeight: '1.2' }],
        '4xl': ['var(--size-36)', { lineHeight: '1.1' }],
        '5xl': ['var(--size-48)', { lineHeight: '1.1' }]
      },
      maxWidth: {
        container: 'var(--width-container-max)'
      },
      fontFamily: {
        h1: ['"Brik%20XL"', '"Brik Condensed"', 'Oswald', 'Impact', 'sans-serif'],
        h2: ['"Brik%20Condensed"', 'Oswald', 'Impact', 'sans-serif'],
        h3: ['"Brik%20Condensed"', 'Oswald', 'Impact', 'sans-serif'],
        h4: ['"Oswald VariableFont Wght"', 'Oswald', 'system-ui', 'sans-serif'],
        h5: ['"Oswald VariableFont Wght"', 'Oswald', 'system-ui', 'sans-serif'],
        h6: ['"Oswald VariableFont Wght"', 'Oswald', 'system-ui', 'sans-serif'],
        p: ['"Oswald VariableFont Wght"', 'Oswald', 'system-ui', 'sans-serif'],
        sans: ['"Oswald VariableFont Wght"', 'Oswald', 'system-ui', 'sans-serif'],
        display: ['"Brik%20XL"', '"Brik Condensed"', 'Oswald', 'Impact', 'sans-serif']
      }
    }
  }
}

